anker/bot/sticker_storage.py: a workaround for get_sticker_set
The issues is described here:
https://github.com/eternnoir/pyTelegramBotAPI/issues/2212

The error I got was:
`TypeError: StickerSet.__init__() missing 2 required positional
arguments: 'is_animated' and 'is_video'`

Since the bot is not using `is_animated` nor `is_video` I can define
these fields directly in the reply.